### ISSUE TITLE
Incorrect output when vars are set for all group

### ISSUE THREAD

**Issue by mzpqnxow** [appuio/ansible-ini2yaml#13]
Hello, thanks for this tool- it was a great easy time-saver when transitioning some rather complex ini format files to yaml

When I used the script, it worked perfectly with one minor exception. I reduced the input to make it simpler to reproduce:

```ini
[group1]
test123

[group2]
test456

[all:vars]
ansible_ssh_user=root
```

This produces:

```yaml
all:
  children:
    all:
      children:
        group1: {}
        group2: {}
      vars:
        ansible_ssh_user: root
    group1:
      hosts:
        test123: {}
    group2:
      hosts:
        test456: {}
```

Ansible doesn't like this and bombs out because `all` occurs as a child of itself. It can be easily fixed manually:

```yaml
all:
  vars:
    ansible_ssh_user: root
  children:
    group1:
      hosts:
        test123: {}
    group2:
      hosts:
        test456: {}
```

I think there should be special logic to treat `all` differently since it has special meaning to ansible- everything is implicitly a child of all as you probably know. If you're interested I'll try to send a PR when I have time
