### ISSUE TITLE
not converting facts

### ISSUE THREAD

**Issue by 21h** [appuio/ansible-ini2yaml#2]
**input:**
```
[myhost1]
myhost1.me ansible_host=myhost1.me ansible_user=ubuntu

[myhost2]
myhost2.me ansible_host=myhost2.me ansible_user=ubuntu
```

**output:**
```
all:
  children:
    myhost1:
      hosts:
        myhost1.me: {}
    myhost2:
      hosts:
        myhost2.me: {}
```
